version: '3.7'
services:
  app-server:
    image: springboot-container-c
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"
    restart: always
    depends_on:
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/lawn_care?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
#    networks: # Networks to join (Services on the same network can communicate with each other using their name)
#      - backend

  # Database Service (Mysql)
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "4002:3306"
    restart: always
    environment:
      MYSQL_DATABASE: lawn_care
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
 #     - db-data:/var/lib/mysql
      - ./data.sql:/docker.entrypoint-initdb.d
    command: mysqld
#    networks:
#      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-server
    ports:
      - "4000:4000"

# Volumes
#volumes:
 # db-data:

#networks:
#  backend:
#    driver: bridge